# Generated by Django 5.0.6 on 2024-06-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('icon', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('icon', models.TextField()),
                ('startDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='home')),
                ('name', models.CharField(max_length=100)),
                ('introduction', models.TextField()),
                ('profilePicture', models.ImageField(upload_to='profilePicture/')),
                ('socials', models.ManyToManyField(to='api.social')),
                ('technologies', models.ManyToManyField(to='api.technology')),
            ],
        ),
        migrations.CreateModel(
            name='KnowTechs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techs', models.ManyToManyField(to='api.technology')),
            ],
        ),
    ]
