# Generated by Django 5.0.6 on 2024-06-07 11:01

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=250)),
                ('companyUrl', models.URLField()),
                ('companylogo', models.ImageField(upload_to='companyLogo/')),
                ('role', models.CharField(max_length=250)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('data', models.DurationField()),
                ('technologies', models.ManyToManyField(to='api.technology')),
            ],
            options={
                'verbose_name': 'Experiência',
                'verbose_name_plural': 'Experiências',
            },
        ),
    ]
