# Generated by Django 5.0.6 on 2024-06-07 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_workexperience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='data',
        ),
    ]
